# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ps_2MpvuuMUTJCEGFMglyOWfC1ln117e
"""

def download_wine_data(urls):
  import os
  from pathlib import Path
  from urllib.parse import urlparse
  import requests

  Path('./data').mkdir(exist_ok=True)

  for url in urls:
    r = requests.get(url, stream = True)
    p = urlparse(url)
    filename = os.path.basename(p.path)
    with open('./data/{}'.format(filename), 'wb') as file:  
      for block in r.iter_content(chunk_size = 1024): 
        if block:  
          file.write(block)

def pull_data():
  red_url = 'https://scicorianjit.blob.core.windows.net/njit/winequality-red.csv'
  white_url = 'https://scicorianjit.blob.core.windows.net/njit/winequality-white.csv'
  data_urls = [red_url, white_url]
  download_wine_data(data_urls)

pull_data()